spring:
  application:
    name: fuel-analysis-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true


server:
  port: 8002


